name: Visual regression tests with Netlify

on:
  pull_request_target:
    types: [labeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:

    runs-on: ubuntu-latest

    if: |
      ( github.repository == 'optuna/optuna-visualization-regression-tests' ) &&
      (
         contains(github.event.pull_request.labels.*.name, 'safe-to-run-visual-regression-tests') ||
         ( github.event_name == 'workflow_dispatch' )
      )

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Optuna
      run: |
        pip install -U pip
        pip install --progress-bar off .
        git clone https://github.com/optuna/optuna.git
        pip install optuna/
    - name: Install Optuna visual regression
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        python visual_regression_tests.py --heavy --output-dir ./public
      env:
        OMP_NUM_THREADS: 1
    - uses: actions/upload-artifact@v2
      with:
        name: built-html
        path: |
          ./public
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2
      with:
        publish-dir: './public'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
